import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import DanielCard from "@/components/Daniel.card";
import JonathanCard from "@/components/Jonathan.card";
import PatrickCard from "@/components/Patrick.card";
import JeantteCard from "@/components/Jeantte.card";
import KiraCard from "@/components/Kira.card";
import "animate.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Testimonials grid section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className="sm:grid sm:grid-cols-2 sm:grid-rows-4 sm:mb-4  lg:grid-cols-4 lg:grid-rows-2 lg:w-[960px] lg:h-[576px] ">
        <DanielCard />
        <JonathanCard />
        <JeantteCard />
        <PatrickCard />
        <KiraCard />
      </main>
    </>
  );
}
